### ISSUE TITLE
Still a few issues with Mules

### ISSUE THREAD

**Issue by FormBurden** [Vectorial1024/v1024_civilian_fleets#14]
It seems when trying to create a fleet with Supply Mules after a while the fleet gets disbanded and put back into "Unassigned Ships". This is just regular trader ships. And the supply mules aren't assigned to a station if that matters, just supplying the organization when need be. 

Regular Travel Mule fleets work like they should and do not get disbanded. I have yet to try station or Distribution fleets because I don't really use them that much. Will keep testing.

**Comment by Vectorial1024** [comment]
The vanilla ones (i.e. Trading Fleet, Mining Fleet, and Distribution Fleet) should work just fine since they use vanilla orders; if they don't work then maybe the default order itself needs work.

I feel like we may need to take things to the Mules and Warehouses Extended repo for this (link: https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended). I am guessing something like

```
Supply Mule default behavior
    init
        if (is assigned to someone else)
            remove assignment
        endif
        other init stuff
    actions
        the main part of the script
```

so, when my side decides to copy commands (I do it by a `create_order` command) then the Mule script starts over, and un-assigns itself from the commander, disbanding the entire fleet.

Maybe I could make use of the rarely-used `edit_order_param`, or maybe I can ask the Mules team if they can exclude the civilian fleet cases on their side.

**Comment by FormBurden** [comment]
Oh I see, that could possibly work. But yeah may have to get into contact with them possibly to get it fixed.

**Comment by Vectorial1024** [comment]
Optionally, refer to https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended/issues/56 for more info. Leaving this open for the time being.

**Comment by bhayden53** [comment]
Happy to work with you all to get mules in line. If at all possible, I would like to leave the functionality in the supply mule for people who may not use civilian fleets to be able to copy their orders to a big list of subordinates. Right now I'm not sure how to detect that we're being managed by civilian fleets and avoid unassigning the commander. It is being investigated.

**Comment by Vectorial1024** [comment]
I've posted an update over at https://github.com/Misunderstood-Wookiee/Mules-and-Warehouses-Extended/issues/56 , containing a proposed adjustment on the Mules' side of things.

**Comment by bhayden53** [comment]
testing now, trying to sneak this into an unrelated bugfix release for today

**Comment by bhayden53** [comment]
It looks like in civ fleets your max jumps value is being copied in as null

**Comment by bhayden53** [comment]
But otherwise, on our side this is working fine.

**Comment by bhayden53** [comment]
```[=ERROR=] 474127.92 Error in MD cue md.CivilianFleets_Signals.Signal_SyncOrders<inst:8e0db7>: Property lookup failed: $fromShip_DefaultOrder.maxDist_FromCommander
* $fromShip_DefaultOrder == order<0x493e> (id=SupplyMule, owner=[0x4baa3], state=ready)
* Expression: $fromShip_DefaultOrder.maxDist_FromCommander
* Action: <set_value>, line 398```

**Comment by Vectorial1024** [comment]
Thanks for pointing out the bug! Will be patching it quickly.

**Comment by Vectorial1024** [comment]
With v2.02 available and fixing the bug, there should be no leftover problems now.

Closing this for now.

**Comment by FormBurden** [comment]
Yep I can now confirm everything is fine now.
