### ISSUE TITLE
Is it possible to allow editing behaviors of assigned ships?

### ISSUE THREAD

**Issue by AqlaSolutions** [Vectorial1024/v1024_civilian_fleets#29]
So I can change their parameters.

**Comment by Vectorial1024** [comment]
It is possible to use `<edit_order_params order="a" param"b" value="c" />` to modify a parameter of the given order (can be default order, can be regular order), where `a` is the variable containing the order, `b` is the identifier of the involved parameter, and `c` is the value to set `b` to. An example is `<edit_order_param order="$ship.defaultorder" param="'maxbuy'" value="4" />`, which would modify the parameter `maxbuy` of the default order of `$ship` to a value of `4`.

Note that you should check what the given order variable is (i.e., what is the id?) before executing this command, otherwise there may be "parameter not found" errors.

Additionally, use `<set_order_syncpoint_reached order="$ship.order"/>` after `<edit_order_params />` to tell the game to update the order UI of `$ship`.

Refer to `/libraries/common.xsd` in your X4 source files for more information.

**Comment by AqlaSolutions** [comment]
Oh, I meant to edit inside the game actually. Sorry for misleading. When I have a tatertrader ship assigned to a station as a trader role, I can't edit its behavior anymore. If I unassign it all its settings are lost so editing things is painful. Can it be hacked somehow? Or perhaps a menu item to unassign a ship without reseting its behavior.

**Comment by Vectorial1024** [comment]
Oh, I see. This is a rather common question around here.

Perhaps you may try Subordinate Order Access by Berserk Knight:

https://www.nexusmods.com/x4foundations/mods/289

It should allow you to modify the details of your ships's behavior even if they are assigned to someone else.

**Comment by AqlaSolutions** [comment]
This mod is not suitable for current 3.1 version though I managed to fix it. Anyway, it works for me)

**Comment by Vectorial1024** [comment]
Glad to have helped!
