### ISSUE TITLE
Suggestion: make auto renaming use anchor sector if available

### ISSUE THREAD

**Issue by americanslon** [Vectorial1024/v1024_civilian_fleets#30]
In addition to the role.

Example: Argon Prime Trading Fleet 1.

**Comment by Vectorial1024** [comment]
Reading your suggestion, I can already come up with a format. For example, we can have fleet names like "Civilian [number] Trading Fleet @ Argon Prime". I hope the game can handle a "@" in fleet names...

Still, I'd rather not touch this right now, because:

1. Just like ware baskets (this was suggested before too, to insert ware basket in the fleet names), anchor spaces are not standardized (but are very common); this can be handled better, but it would require me to restructure the code
2. Real life is becoming increasingly unstable, unpredictable, and harmful; will I even survive till the next month? This has nothing to do with the killer-virus, by the way.

Even still, I'm leaving this open because this is a good suggestion. Either I come around in the future and have a look again, or (if it really happened) someone substitute me by themselves and continue with the work.

**Comment by americanslon** [comment]
I was trying to decipher what you mean and how to appropriately respond and then I noticed your actual name...

My wife's parents are from HK, I actually just went for the firs time in spring 2019. Beautiful city. Stay strong!

**Comment by Vectorial1024** [comment]
Thank you! I often underestimate the influence that Hong Kong may have in the non-Asian world. It somehow felt as if the city is becoming less important by the day, even before this year-long real-life fiasco... Good of you to have witnessed the beauty of the city together with many of us.

Still, leaving this open, until when everything settles at a new equilibrium.

**Comment by americanslon** [comment]
Originally being from Europe but now living in the US with it's aversion to proper public transportation  your metro system almost made me cry wit joy among other things :)

While I have your attention, how do I defend a civilian fleet? Do the defending ships know to stay with each individual member of the fleet?

**Comment by Vectorial1024** [comment]
Defenders do know to stay with their commander; assigned defenders will defend their commander just as usual. But regarding this, if the civilian commander is killed, there is a chance that the game will pick an escort to promote him to the commander post. In this case, you will have to manually reform the fleet, because then, the other civilian fleet subordinates of the dead commander will become confused about the escort becoming the new commander and lose their default behaviors.

And, in case people asked, the defending ships of a civilian fleet do not act like station defenders, in that they *will not* attempt to automatically escort the other civilian subordinates of the commander (that is how station defenders worked).

**Comment by Vectorial1024** [comment]
I am alive! If there are no problems (confident there are no problems) then Imma merge it in a few days.
