### ISSUE TITLE
Serve Source Only on Mules does not copy over

### ISSUE THREAD

**Issue by FormBurden** [Vectorial1024/v1024_civilian_fleets#35]
Now not entirely sure if Mules would need to be updated or not. But when I have a Travel Mule assigned to a station, and I click "Serve Source Only" button, and do my settings for the rest of the Travel Mule, I assign it to a station, everything is fine. But as soon as I grab another ship to assign them to the leader (that is assigned to the station), so the fleet can get started and orders copied to subordinates, everything gets copied except the "Serve Source Only". 

Thought I'd let you know.

**Comment by FormBurden** [comment]
Oh wait, now that I think about it, it might not need to be copied over, because the leader is the "Serve Source Only", while the subordinates have the same orders, but don't need that option, because it would give them a leader role instead of subordinate.

**Comment by Vectorial1024** [comment]
...yeah, I think I came across a param on the Mules' side that talks about a "source". I was thinking exactly the same thing as you thought, but that if I were to copy the "source" option to everyone in the Mules fleet, the fleet would dissolve itself when it attempts to sync orders because everyone would then assign themselves directly under Source.

I made it such that the "source" param is always false.

Closing this for now.
