### ISSUE TITLE
Support for the Random Trading Mods?

### ISSUE THREAD

**Issue by FormBurden** [Vectorial1024/v1024_civilian_fleets#37]
Hello once again, I was wondering if it would be possible to get support for all three Random Mine/Trade/Supply mods? Mainly because RandomTrade actually has better algorithms than TaterTrader (if you can believe that lol), plus it has its perks that TaterTrader does not. Not like I'm dropping TaterTrader, I still use it, but some scenarios RandomTrader is better.

Thanks for your time.

**Comment by Vectorial1024** [comment]
It may not seem obvious here on GitHub or on Steam (more obvious on Nexus), but I don't plan to support the Random Bois. This is mainly because the maker of the Random Bois have implemented some sort of "order sync" feature inside the Bois out-of-the-box, so it doesn't seem efficient for me to also include the Bois into our order syncing scheme.

At some moment after I wrote the order sync code for the Random Bois (those code is still there in the MD file, go search e.g. `RandomTrade` in it), I noticed the self-made order syncing feature, so I put a `chance="0"` on my side to block my code from being run.

(But then whether their self-made order sync feature works, I'm, ahem... interested to see...)

Closing this for now.
