### ISSUE TITLE
Construction Ship orders don't go to fleet

### ISSUE THREAD

**Issue by FormBurden** [Vectorial1024/v1024_civilian_fleets#38]
Thought I'd let you know that when having several Construction vessels , and having the "Find Build Tasks" task on, if you start a fleet with them, the orders do not go to the subordinates.

**Comment by Vectorial1024** [comment]
Yes this is true, but to be honest, I am not very sure myself how that "Find build tasks" work, or how users would use them. I personally would first set up a station construction yard, and then manually hire a builder ship/assign one of my builder ships to it. Never used the "Find build tasks" myself.

If I were to look at the script itself then it seems "find build tasks" will wait for some MD script to set the buildmodue for it to deploy to. My guess at this moment is that "find build tasks" is only intended for NPC builders, but I could be wrong.

Leaving this open for now because idk what is going on.

**Comment by FormBurden** [comment]
Well mainly why I would use it, is lets say I have 5 Construction vessels right. I would put them to Find Build Task, create the fleet, and they'll just roam to sectors looking for work. Then when I create a station, I can quickly pick one of them and such. Essentially it's just for UI management. 

The Find Build Task is more of a thing when you're playing for nearly a day. Because early on in the game each of the main factions have like 15-20 of these vessels, but literally a day into the game when the Xenon and other wars are raging on, each faction literally only has a handful left, if not any. Idk why they don't rebuild, but w/e. But yeah, when you get to that point the Find Build Task actually works, and the NPCs use your vessels.

**Comment by Vectorial1024** [comment]
If we could confirm that the Find Build Tasks is actually useful then it should be possible to implement the relevant buttons.

Copied from what is shown in the vanilla `scriptproperties.html` file, I could see the following possible assignments already available in vanilla, with, of course, some of them unused:

- defence
- attack
- interception
- mining
- trade
- build
- supplyfleet
- tradeforbuildstorage 
- police 
- watchdog

It would seem that this suggestion would utilize the `build` assignment.

**Comment by Vectorial1024** [comment]
Update after many many time:

With X4 v5.0 coming out, I rechecked things again at #59 , and I revisited this issue. It turns out that Find Build Task is something that should work. Here is what I found:

Find Build Task is for constructors to find NPC build jobs in the same sector as they are at. Every once in a while, existing NPC Build Storage units (if they need a constructor) will broadcast to the sector they are at to see whether any friendly constructor is available. If the constructor is listening to this broadcast (i.e. using Find Build Tasks), then the constructor will accept the job and move to the station plot.

---

When constructors use Find Build Task, but has not found any build tasks, it will use `move.idle`, which means it will wander inside the sector that it is in. I could infer that the way to use builder ships is to:

1. Move them into the correct sector
2. Enable Find Build Tasks

I am not sure whether ships can queue their "change assignment" commands (this I need to check). If they can queue that, then I can add builder fleets to this mod, but if they cannot (i.e. Assign Commander takes effect immediately), then there will be no builder fleets in this mod.
