### ISSUE TITLE
TaterTrader: anchor names

### ISSUE THREAD

**Issue by Vectorial1024** [Vectorial1024/v1024_civilian_fleets#68]
Steam user reports that TaterTrader seems to have added an option to their fleets: fleet anchors.

**Comment by Pasukaru** [comment]
To clarify, since it's called different in the two behaviours that [TaterTrade](https://steamcommunity.com/sharedfiles/filedetails/?id=2082610969) adds:

* For the `TaterTrade` behaviour it's called `Trader Home`.

![grafik](https://user-images.githubusercontent.com/1093680/233173133-bccf95dd-1cf5-41f4-bbe8-7589898a506d.png)


* For the `Dead Tater` behaviour it's called `Anchor space`:

![grafik](https://user-images.githubusercontent.com/1093680/233173237-8b6f744c-8bb8-4f6e-9e83-47f5245b71c2.png)

**Comment by Vectorial1024** [comment]
> Any future change planned to DeadTater fleet name support?

I rechecked my code, it seems I am aware that DeadTater has a "range" param but I totally forgot to use it to print the fleet anchor...

**Comment by Vectorial1024** [comment]
This is now done; wait for the update.

**Comment by Vectorial1024** [comment]
Update released.
